### ISSUE TITLE
Having issues with production build on heroku

### ISSUE THREAD

**Issue by dlai0001** [keydunov/ember-cli-moment#2]
-----> Building Ember CLI application production distribution
bower loader#1.0.1            mismatch Version declared in the json (0.0.0) is different than the resolved one (1.0.1)
bower handlebars#~1.3.0   invalid-meta handlebars is missing "ignore" entry in bower.json
bower ember-resolver#~0.1.7   mismatch Version declared in the json (0.1.6) is different than the resolved one (0.1.7)
bower ember-qunit#0.1.8   invalid-meta ember-qunit is missing "main" entry in bower.json
bower ember#1.7.0         invalid-meta ember is missing "ignore" entry in bower.json
bower ember-data#~1.0.0-beta.7     invalid-meta ember-data is missing "ignore" entry in bower.json
       version: 0.0.44
       BuildingBuild failed.
       ENOENT, no such file or directory 'node_modules/ember-cli-moment/node_modules/'
       Error: ENOENT, no such file or directory 'node_modules/ember-cli-moment/node_modules/'
           at Object.fs.readdirSync (fs.js:659:18)
           at walkSync (/tmp/build_15580794-63f4-46e0-9116-167aa57736ca/node_modules/ember-cli/node_modules/walk-sync/index.js:14:20)
           at /tmp/build_15580794-63f4-46e0-9116-167aa57736ca/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:26:26
           at $$$internal$$tryCatch (/tmp/build_15580794-63f4-46e0-9116-167aa57736ca/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
           at $$$internal$$invokeCallback (/tmp/build_15580794-63f4-46e0-9116-167aa57736ca/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
           at $$$internal$$publish (/tmp/build_15580794-63f4-46e0-9116-167aa57736ca/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:453:11)
           at $$rsvp$asap$$flush (/tmp/build_15580794-63f4-46e0-9116-167aa57736ca/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1531:9)
           at process._tickCallback (node.js:419:13)

 !     Push rejected, failed to compile Ember CLI app

To git@heroku.com:powerful-everglades-9282.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@heroku.com:powerful-everglades-9282.git'

davids-mbp: dlai$ git status

**Comment by keydunov** [comment]
Do you use this buildpack https://github.com/tonycoco/heroku-buildpack-ember-cli?

**Comment by dlai0001** [comment]
Yup I used that one.  
Last night I was debugging it some more and I started a new project without the ember-cli-bootstrap and I didn't get that error (got a different one, but I think it might be attributed with the stub api not running on heroku).  I don't think that's quite it, but maybe there's some strange thing going on post uglify when I have bootstrap and moment ember-cli add-on's together.

**Comment by keydunov** [comment]
I have tried ember-cli-moment and ember-cli-bootstrap together (this sample app https://github.com/keydunov/ember-cli-moment-example) and it works fine on heroku. Can you please more provide more details about your setup or fork sample app and try to reproduce error.

**Comment by keydunov** [comment]
ember-cli-moment has been deprecated in favor of [ember-moment](https://github.com/stefanpenner/ember-moment).
